# Preview this course: https://dev-doctor.cf/

# The icon of the course should be named with this name and located in this directory
icon: null

# The name of the course. You can see it in the title or in the list
name: HTML Basics

# The author. It will appear on the front page and on the courses list
author: FreshVlay

# The description of the course which can be seen in the list of the courses and the intro page.
description: >
  Hier lernst du die Basics von HTML
# The current category of the course. You can see the categories in the list
category: []

# The language of the course. You can see a flag as a badge of the course.
lang: de

# Controls if the course is shown in the list
private: true

# The course. See the preview to understand all config entries
parts:
  - name: Part 1
    items:
    - name: Welcome
      description: Welcome to the course
      type: video
      url: https://youtu.be/ScMzIvxBSi4
    - name: Text
      type: text
      text: >
        Here you can write something. Markdown is supported!
    - name: Quiz
      # Optional: Max time in seconds (here: 10 minutes)
      time: 600
      questions:
      - title: Question 1 title
        description: Question 1 description
        answers:
        - name: A
          description: A description
        - name: B
          description: B description
        - name: C
          description: C is correct
          correct: true
        - name: D
          description: Multiple correct answers are also possible
          correct: true
